# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d5aac58dc1e0410a61a3f4ba01bd67d07a5ef6d603fcead7cf75401d204c9f2de3367ad66656de2c27ac000ee0ec681d42d5e628bad59e2387d3c72fbba1030

test:
  secret_key_base: 5e2c3dd1674b1e96b1b0f41e99b6753ce5346ae97d756a80d75ddcf97f31e5a1b52cfa7d4cd6e4f741447c7887e502b7e12598803e33a4b0be99e34d2f79f84c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
